version: "3"

services:
  localtest:
    build:
      context: .
      args:
        build: debug
    environment:
      - "BIND_API_MODE=standalone"
    # volumes:
    #   - ".:/app"
    command: [ ./node_modules/.bin/mocha, ./test/adapter-local-test.js ]
  local:
    build: .
    environment:
      - "BIND_API_MODE=standalone"
    # volumes:
    #   - ".:/app"
    ports:
      - "53:53/udp"
      - "3000:3000"
  docker:
    build: .
    ports:
      - 3000:3000
    volumes:
      - "./mock/data:/data"
      - "./mock/etc:/etc/bind"
      - "./mock/db:/var/lib/bind"
  mockbind:
    image: reekoheek/bind
    ports:
      - 53:53/udp
    volumes:
      - "./mock/etc:/etc/bind"
      - "./mock/db:/var/lib/bind"
